### ISSUE TITLE
This application does not work.

### ISSUE THREAD

**Issue by yousaid** [Vintharas/talk-angular-material#1]
Thought you should know, but this application does not compile. Tested  on both Windows and Mac environments.
Any ideas? Were able to get it to run?
cheers,

**Comment by vintharas** [comment]
Hi @yousaid ! ^_^

The application was using a deprecated version of the angular cli (the former <code>angular-cli</code> instead of the current <code>@angular/cli</code>)

I have updated and now it should work:

1. Clone it
2. npm install
3. ng serve --open

And you should be able to see the same app in your computer. ^_^
